
name: widget-server-pipe

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout 
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          # estou usando WS_ACCESS_KEY_ID ao invés de AWS_ACCESS_KEY_ID porque
          # coloquei errado no github e iria demorar para corrigir, então deixei assim mesmo
          aws-access-key-id: ${{ secrets.WS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.WS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push the image to AWS ECR
        id: build-and-push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
        run: |
          docker build -t widget-server:v3 .
          docker tag widget-server:v3 ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:v3
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:v3